spring:
  application:
    name: api-coffee

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload:
    dir: uploads
  storage:
    type: local

---
# Perfil de Desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true